name = "wenluo-cloudflare"
compatibility_date = "2024-01-01"

pages_build_output_dir = "public"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "DATA"
id = "cb14318386c34f3b9233eac196d7f4d7"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "DATA"
id = "cb14318386c34f3b9233eac196d7f4d7"